# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.6.1']

    steps:
         # 1. Check out the repository
      - uses: actions/checkout@v4
         # 2. Check out the dependent repository
      - name: Checkout dependent repository
        uses: actions/checkout@v4
        with:
          repository: 'utaresearch/nwsrfs-hydro-models'
          path: dependent-repo
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install curl-devel and gfortran
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev
          sudo apt install gfortran
          sudo apt install libuv1-dev
      - name: Install dependencies
        run: |
          packages <- c('pkgdown', 'xfun', 'import', 'devtools', 'RPostgres', 'gridExtra', 'fitdistrplus', 'hydroEvents', 'remotes', 'rcmdcheck')
          install.packages(packages)
          remotes::install_deps(dependencies = TRUE)
          devtools::install_github('utaresearch/nwsrfs-hydro-models',subdir='nwsrfs_r')
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
